name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar
      - name: Get Minecraft Version
        id: mcver
        run: echo "mcversion=$(./gradlew -q printMinecraftVersion)" >> "$GITHUB_OUTPUT"
      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: folia-paperclip
          path: build/libs/folia-paperclip-*-mojmap.jar
      - name: Create Release
        if: success() && github.ref_name == github.event.repository.default_branch && github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Folia ${{ steps.mcver.outputs.mcversion }} #${{ github.run_number }}"
          body: |
            Folia build for Minecraft ${{ steps.mcver.outputs.mcversion }}
            Commit: ${{ github.sha }}
          files: build/libs/folia-paperclip-*-mojmap.jar
          generate_release_notes: false
